### ISSUE TITLE
Converting FOA Format from STARSS23 Dataset to Planar Circular Microphone Array Format Using spaudiopy

### ISSUE THREAD

**Issue by yu0o0** [chris-hld/spaudiopy#33]
Hi everyone,
I’m currently working on a project that involves spatial audio processing using the STARSS23 dataset. My goal is to convert the FOA (First-Order Ambisonics) format audio files from this dataset into a format compatible with a planar circular four-microphone array.

The planar circular microphone array I’m using has the following coordinates in spherical format:

Mic 1: (0°, 0°, 1)
Mic 2: (90°, 0°, 1)
Mic 3: (180°, 0°, 1)
Mic 4: (270°, 0°, 1)
I’ve read that spaudiopy is a powerful tool for such spatial audio processing tasks, and I believe it can help with this conversion. However, I’m looking for guidance on how to effectively decode FOA signals to match this specific planar circular microphone configuration.

If anyone has experience with this kind of conversion or can point me to relevant documentation or examples using spaudiopy, I would greatly appreciate your help.

Thanks in advance for your assistance!

Best regards

**Comment by chris-hld** [comment]
Hi! I think you are best off with a conversion to circular harmonics, if you want to go to any harmonics domain from this array geometry.
Going from a planar circular array to spherical harmonics is not straight forward, as a planar array can not directly capture elevation information. That being said, there are some approaches that attempt such conversion. Feel free to reach out if you would like more information, I could try to point to a few papers.
Circular harmonics are not (yet) implemented here, although it should be a straight forward adaption of the existing, closing the current issue therefore as out of scope. 
Feel free to reach out or re-open!
