### ISSUE TITLE
problem with matplotlib

### ISSUE THREAD

**Issue by SmartWaddles** [chris-hld/spaudiopy#5]
Hello. It looks like this lib uses matplotlib to draw 3d environment model.
But matplotlib throws an error: 
`NotImplementedError: It is not currently possible to manually set the aspect on 3D axes`
while trying to execute the following code:
```
File "\.conda\envs\vbap_test\lib\site-packages\spaudiopy\plots.py", line 362, in hull_normals
    ax = fig.add_subplot(1, 1, 1, projection='3d', aspect='equal')
```

I'm using matplotlib==3.1.1

**Comment by chris-hld** [comment]
Hi! 
Yes, unfortunately that is a problem. Until matplotlib fixes this, we have to stick with a slightly older version.
If you install this package, this line should take care of it 
https://github.com/chris-hld/spaudiopy/blob/0fe20d060a5af74d4a3ce6a771a733f535386583/setup.py#L28

**Comment by SmartWaddles** [comment]
thanks a lot! I'll make different env for this to use older matplotlib.
Also, thank you very much for these examples:
https://github.com/chris-hld/spaudiopy/tree/master/examples

By the way - can you recommend something to read/watch/play for better understanding of spatial acoustics? Something e.g. like ThinkDSP.
