### ISSUE TITLE
Spherical Hankel function

### ISSUE THREAD

**Issue by egerdem** [chris-hld/spaudiopy#6]
In "mode strength" function :

def spherical_h2(n, z):
        with np.errstate(divide='ignore'):
            return scyspecial.spherical_jn(n, z) **+**  1j * scyspecial.spherical_yn(n, z)

Shouldn't it be minus sign ?
return scyspecial.spherical_jn(n, z) **-**  1j * scyspecial.spherical_yn(n, z)

https://spaudiopy.readthedocs.io/en/latest/_modules/spaudiopy/sph.html#mode_strength

**Comment by chris-hld** [comment]
Oh thank you! Yes that is correct! I accidentally implemented the [spherical hankel function of the first kind ](http://mathworld.wolfram.com/SphericalHankelFunctionoftheFirstKind.html), rather then [of the second kind](http://mathworld.wolfram.com/SphericalHankelFunctionoftheSecondKind.html).
In this particular case it shouldn't cause problems, but I will correct and extend this.

**Comment by chris-hld** [comment]
Fixed in d53f8e66a3b9121937d8ee92b8156c1d521db877

**Comment by egerdem** [comment]
Oh I see, thanks :)

Chris Hold <notifications@github.com>, 19 Ara 2019 Per, 12:37 tarihinde
şunu yazdı:
